USE [master]
GO

/****** Object:  Database [vSmartNotices]    Script Date: 5/27/2015 8:50:01 AM ******/
CREATE DATABASE [vSmartNotices] ON  PRIMARY 
( NAME = N'vSmartNotices', FILENAME = N'F:\DB files\vSmartNotices.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'vSmartNotices_log', FILENAME = N'L:\Log Files\vSmartNotices_log.ldf' , SIZE = 17408KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [vSmartNotices] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vSmartNotices].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vSmartNotices] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vSmartNotices] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vSmartNotices] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vSmartNotices] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vSmartNotices] SET ARITHABORT OFF 
GO

ALTER DATABASE [vSmartNotices] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [vSmartNotices] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vSmartNotices] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vSmartNotices] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vSmartNotices] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vSmartNotices] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vSmartNotices] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vSmartNotices] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vSmartNotices] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vSmartNotices] SET  DISABLE_BROKER 
GO

ALTER DATABASE [vSmartNotices] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vSmartNotices] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vSmartNotices] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vSmartNotices] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vSmartNotices] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vSmartNotices] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [vSmartNotices] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vSmartNotices] SET RECOVERY FULL 
GO

ALTER DATABASE [vSmartNotices] SET  MULTI_USER 
GO

ALTER DATABASE [vSmartNotices] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vSmartNotices] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vSmartNotices] SET  READ_WRITE 
GO

